server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: api/users
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: orders
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}
