server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: login-event-aggregator
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
